# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: embedded-ams
      url-base: https://github.com/Embedded-AMS/

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 2d060feb51accfd31a797d178287682e208ce16c
      import:
        name-allowlist:
          - cmsis
          - hal_stm32

    - name: EmbeddedProto
      remote: embedded-ams
      revision: 3.4.2
      submodules: true
      path: modules/EmbeddedProto
