name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.5
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: app

      - name: Initialize
        working-directory: app
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: app
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Twister Tests
        working-directory: app
        run: |
          west twister -T tests --integration
