name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.12
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app

      - name: Initialize workspace
        working-directory: app
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Install tools
        working-directory: modules/EmbeddedProto
        run: |
          sudo apt update
          sudo apt install -y unzip curl python3.10-venv gcc-12 g++-12 gcc-12-multilib g++-12-multilib
          curl -L -O https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip
          sudo unzip -o protoc-25.1-linux-x86_64.zip -d /usr/local
          python setup.py
          sudo ln -s -f /usr/bin/gcc-12 /usr/bin/gcc
          sudo ln -s -f /usr/bin/g++-12 /usr/bin/g++

      - name: Build firmware
        working-directory: app
        run: |
          west build -b serial_temp_sens app

      - name: Twister Tests
        working-directory: app
        run: |
          west twister -T tests --inline-logs --integration

      - name: Archive MCU image
        uses: actions/upload-artifact@v4
        with:
          name: SerialTempSens_image
          path: |
            ./app/build/zephyr/zephyr.hex

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: SerialTempSens_image

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./SerialTempSens_image/zephyr.hex
