name: Release

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Built FW Image
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          branch: main
          event: push
          name: SerialTempSens_image

      - name: Rename File
        run: |
          mkdir release
          cp ./zephyr.hex release/serialTempSens_${{ github.ref_name }}.hex

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: release/serialTempSens_${{ github.ref_name }}.hex
