name: Build

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Built FW Image
        uses: actions/download-artifact@v4
        with:
          name: SerialTempSens_image

      - name: Rename File
        run: |
          mkdir release
          cp ./SerialTempSens_image/zephyr.hex release/serialTempSens_${{ github.ref_name }}.hex

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: release/serialTempSens_${{ github.ref_name }}.hex
